### ISSUE TITLE
Support custom config directory hierarchy via environment variables

### ISSUE THREAD

**Issue by doganulus** [openSUSE/libeconf#201]
Studying the implementation, I see the `libeconf` design based on two-level configuration hierarchy, `/usr` and `/etc`. 

I am wondering if you see any benefit to generalizing this design into a multi-level hierarchy configured using user-defined environment variables such as

```bash
PROJECT_CONFIG_HOME="$HOME/.config/<project>"
PROJECT_CONFIG_DIRS="/etc/<project>:/run/<project>:/usr/<vendorlib>/<project>"
```

Can this be a useful feature for the `libeconf` project?

**Comment by thkukuk** [comment]
> Studying the implementation, I see the `libeconf` design based on two-level configuration hierarchy, `/usr` and `/etc`.

It's at minimum a three level hierachy, if not even more. It's more complex, as explained in the README. See also the UAPI group spec: [Configuration Files Specification](https://uapi-group.org/specifications/specs/configuration_files_specification/)

> I am wondering if you see any benefit to generalizing this design into a multi-level hierarchy configured using user-defined environment variables such as

libeconf is used by setuid applications and for authentication, so using directories specified by environment variables is a no-go.
The search paths are defined by the application when calling libeconf.
What you can do is to enhance the interface, so that applications can set additional directories inside the home directory of the user. Applications itself should know if it is safe to use user provided configuration files or not.

**Comment by doganulus** [comment]
Thank you for your answer @thkukuk. I have noted the concern regarding environment variables.

Yes, you are right. [This example](https://github.com/openSUSE/libeconf/blob/master/example/example.c) deceived me, which uses the deprecated `econf_readDirs` function. 

Yet, doesn't the implementation still fix the config directories somewhat, except for the `dist_dir`? This may be intentional but I still would like to ask what the drawbacks could be when generalizing the current signature of 
```c
econf_err readConfigHistoryWithCallback(
  ...,
  const char *dist_conf_dir,
  const char *run_conf_dir,
  const char *etc_conf_dir,
  ...
);
```
with
```c
econf_err readConfigHistoryWithCallback(
  ...,
  const char **conf_dirs,
  ...
);
```
and the application can set the `conf_dirs` variable in the code or overwrite using environment variables later if it is appropiate.

**Comment by schubi2** [comment]
You can set it now. Have a look to the release notes:
https://github.com/openSUSE/libeconf/releases/tag/v0.7.0
